# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controller_v2_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lbl_state = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_state.setFont(font)
        self.lbl_state.setObjectName("lbl_state")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_state)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lbl_address = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_address.setFont(font)
        self.lbl_address.setObjectName("lbl_address")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_address)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lbl_connection = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_connection.setFont(font)
        self.lbl_connection.setObjectName("lbl_connection")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_connection)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 2, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.gridLayout.addWidget(self.groupBox, 0, 3, 2, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMaximumSize(QtCore.QSize(226, 16777215))
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txt_pulses = QtWidgets.QLineEdit(self.frame)
        self.txt_pulses.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_pulses.setReadOnly(True)
        self.txt_pulses.setObjectName("txt_pulses")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_pulses)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txt_repeats = QtWidgets.QLineEdit(self.frame)
        self.txt_repeats.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_repeats.setReadOnly(True)
        self.txt_repeats.setObjectName("txt_repeats")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_repeats)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txt_pri_pw = QtWidgets.QLineEdit(self.frame)
        self.txt_pri_pw.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_pri_pw.setReadOnly(True)
        self.txt_pri_pw.setObjectName("txt_pri_pw")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_pri_pw)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.txt_prepulse = QtWidgets.QLineEdit(self.frame)
        self.txt_prepulse.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_prepulse.setReadOnly(True)
        self.txt_prepulse.setObjectName("txt_prepulse")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_prepulse)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.txt_x_amp_delay = QtWidgets.QLineEdit(self.frame)
        self.txt_x_amp_delay.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_x_amp_delay.setReadOnly(True)
        self.txt_x_amp_delay.setObjectName("txt_x_amp_delay")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_x_amp_delay)
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.txt_l_amp_delay = QtWidgets.QLineEdit(self.frame)
        self.txt_l_amp_delay.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_l_amp_delay.setReadOnly(True)
        self.txt_l_amp_delay.setObjectName("txt_l_amp_delay")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_l_amp_delay)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.txt_rex_delay = QtWidgets.QLineEdit(self.frame)
        self.txt_rex_delay.setMinimumSize(QtCore.QSize(55, 0))
        self.txt_rex_delay.setReadOnly(True)
        self.txt_rex_delay.setObjectName("txt_rex_delay")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_rex_delay)
        self.horizontalLayout.addWidget(self.frame)
        self.table_pulse_params = QtWidgets.QTableWidget(self.frame_4)
        self.table_pulse_params.setMinimumSize(QtCore.QSize(390, 0))
        self.table_pulse_params.setMaximumSize(QtCore.QSize(392, 16777215))
        self.table_pulse_params.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_pulse_params.setAutoScroll(True)
        self.table_pulse_params.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_pulse_params.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_pulse_params.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.table_pulse_params.setObjectName("table_pulse_params")
        self.table_pulse_params.setColumnCount(4)
        self.table_pulse_params.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(3, item)
        self.table_pulse_params.horizontalHeader().setDefaultSectionSize(97)
        self.horizontalLayout.addWidget(self.table_pulse_params)
        self.gridLayout.addWidget(self.frame_4, 2, 0, 1, 4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_address = QtWidgets.QLineEdit(self.frame_5)
        self.txt_address.setObjectName("txt_address")
        self.horizontalLayout_3.addWidget(self.txt_address)
        self.but_connect = QtWidgets.QPushButton(self.frame_5)
        self.but_connect.setObjectName("but_connect")
        self.horizontalLayout_3.addWidget(self.but_connect)
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_5)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setEnabled(True)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txt_bof_exe = QtWidgets.QLineEdit(self.frame_6)
        self.txt_bof_exe.setObjectName("txt_bof_exe")
        self.horizontalLayout_4.addWidget(self.txt_bof_exe)
        self.but_configure = QtWidgets.QPushButton(self.frame_6)
        self.but_configure.setObjectName("but_configure")
        self.horizontalLayout_4.addWidget(self.but_configure)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_6)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_headerfile = QtWidgets.QLineEdit(self.frame_2)
        self.txt_headerfile.setEnabled(True)
        self.txt_headerfile.setObjectName("txt_headerfile")
        self.horizontalLayout_2.addWidget(self.txt_headerfile)
        self.but_headerfile = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_headerfile.sizePolicy().hasHeightForWidth())
        self.but_headerfile.setSizePolicy(sizePolicy)
        self.but_headerfile.setObjectName("but_headerfile")
        self.horizontalLayout_2.addWidget(self.but_headerfile)
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.frame_2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setEnabled(True)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.gridLayout.addLayout(self.formLayout_3, 3, 0, 1, 4)
        self.but_write_3 = QtWidgets.QPushButton(self.centralwidget)
        self.but_write_3.setObjectName("but_write_3")
        self.gridLayout.addWidget(self.but_write_3, 4, 1, 1, 1)
        self.but_write_2 = QtWidgets.QPushButton(self.centralwidget)
        self.but_write_2.setObjectName("but_write_2")
        self.gridLayout.addWidget(self.but_write_2, 4, 2, 1, 1)
        self.but_write = QtWidgets.QPushButton(self.centralwidget)
        self.but_write.setObjectName("but_write")
        self.gridLayout.addWidget(self.but_write, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "State:"))
        self.lbl_state.setText(_translate("MainWindow", "Unknown"))
        self.label_4.setText(_translate("MainWindow", "Address:"))
        self.lbl_address.setText(_translate("MainWindow", "Unknown"))
        self.label_3.setText(_translate("MainWindow", "Connection:"))
        self.lbl_connection.setText(_translate("MainWindow", "Disconnected"))
        self.checkBox.setText(_translate("MainWindow", "Auto-update"))
        self.groupBox.setTitle(_translate("MainWindow", "Clock"))
        self.radioButton.setText(_translate("MainWindow", "Internal"))
        self.radioButton_2.setText(_translate("MainWindow", "External"))
        self.label_7.setText(_translate("MainWindow", "Not Locked"))
        self.checkBox_2.setText(_translate("MainWindow", "Auto-arm"))
        self.label_5.setText(_translate("MainWindow", "PULSES"))
        self.label_6.setText(_translate("MainWindow", "REPEATS"))
        self.label_8.setText(_translate("MainWindow", "PRI PW [μs]"))
        self.label_10.setText(_translate("MainWindow", "PREPULSE [μs]"))
        self.label_12.setText(_translate("MainWindow", "X AMP DELAY [μs]"))
        self.label_14.setText(_translate("MainWindow", "L AMP DELAY [μs]"))
        self.label_15.setText(_translate("MainWindow", "REX DELAY [μs]"))
        item = self.table_pulse_params.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pulse Width"))
        item = self.table_pulse_params.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PRI"))
        item = self.table_pulse_params.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.table_pulse_params.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Frequency"))
        self.but_connect.setToolTip(_translate("MainWindow", "<html><head/><body><p>Establish connection to the TCU with the given IP address</p></body></html>"))
        self.but_connect.setText(_translate("MainWindow", "Connect"))
        self.label_11.setText(_translate("MainWindow", "Bof Exe"))
        self.but_configure.setText(_translate("MainWindow", "Configure"))
        self.label_2.setText(_translate("MainWindow", "Headerfile"))
        self.but_headerfile.setText(_translate("MainWindow", "Browse"))
        self.label_9.setText(_translate("MainWindow", "Address"))
        self.but_write_3.setText(_translate("MainWindow", "FIRE"))
        self.but_write_2.setText(_translate("MainWindow", "ARM"))
        self.but_write.setText(_translate("MainWindow", "Write Registers"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

