# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controller_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(460, 0, 226, 354))
        self.groupBox.setMaximumSize(QtCore.QSize(226, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_state = QtWidgets.QLineEdit(self.groupBox)
        self.txt_state.setReadOnly(True)
        self.txt_state.setObjectName("txt_state")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_state)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.txt_connection = QtWidgets.QLineEdit(self.groupBox)
        self.txt_connection.setReadOnly(True)
        self.txt_connection.setObjectName("txt_connection")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_connection)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txt_pulses = QtWidgets.QLineEdit(self.groupBox)
        self.txt_pulses.setReadOnly(True)
        self.txt_pulses.setObjectName("txt_pulses")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_pulses)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txt_repeats = QtWidgets.QLineEdit(self.groupBox)
        self.txt_repeats.setReadOnly(True)
        self.txt_repeats.setObjectName("txt_repeats")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_repeats)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txt_pri_pw = QtWidgets.QLineEdit(self.groupBox)
        self.txt_pri_pw.setReadOnly(True)
        self.txt_pri_pw.setObjectName("txt_pri_pw")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_pri_pw)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.txt_prepulse = QtWidgets.QLineEdit(self.groupBox)
        self.txt_prepulse.setReadOnly(True)
        self.txt_prepulse.setObjectName("txt_prepulse")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_prepulse)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.txt_x_amp_delay = QtWidgets.QLineEdit(self.groupBox)
        self.txt_x_amp_delay.setReadOnly(True)
        self.txt_x_amp_delay.setObjectName("txt_x_amp_delay")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_x_amp_delay)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.txt_l_amp_delay = QtWidgets.QLineEdit(self.groupBox)
        self.txt_l_amp_delay.setReadOnly(True)
        self.txt_l_amp_delay.setObjectName("txt_l_amp_delay")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txt_l_amp_delay)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 0, 411, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_pulse_params = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_pulse_params.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table_pulse_params.setAutoScroll(True)
        self.table_pulse_params.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_pulse_params.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_pulse_params.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.table_pulse_params.setObjectName("table_pulse_params")
        self.table_pulse_params.setColumnCount(4)
        self.table_pulse_params.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_pulse_params.setHorizontalHeaderItem(3, item)
        self.table_pulse_params.horizontalHeader().setDefaultSectionSize(97)
        self.horizontalLayout.addWidget(self.table_pulse_params)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(300, 340, 105, 101))
        self.frame.setMaximumSize(QtCore.QSize(105, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.but_override = QtWidgets.QPushButton(self.frame)
        self.but_override.setObjectName("but_override")
        self.verticalLayout.addWidget(self.but_override)
        self.but_refresh = QtWidgets.QPushButton(self.frame)
        self.but_refresh.setObjectName("but_refresh")
        self.verticalLayout.addWidget(self.but_refresh)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 330, 196, 105))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(196, 105))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.but_fire_abort = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_fire_abort.sizePolicy().hasHeightForWidth())
        self.but_fire_abort.setSizePolicy(sizePolicy)
        self.but_fire_abort.setMinimumSize(QtCore.QSize(85, 85))
        self.but_fire_abort.setAutoFillBackground(False)
        self.but_fire_abort.setObjectName("but_fire_abort")
        self.gridLayout.addWidget(self.but_fire_abort, 0, 2, 1, 1)
        self.but_arm_disarm = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_arm_disarm.sizePolicy().hasHeightForWidth())
        self.but_arm_disarm.setSizePolicy(sizePolicy)
        self.but_arm_disarm.setMinimumSize(QtCore.QSize(85, 85))
        self.but_arm_disarm.setMaximumSize(QtCore.QSize(85, 16777215))
        self.but_arm_disarm.setObjectName("but_arm_disarm")
        self.gridLayout.addWidget(self.but_arm_disarm, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 691, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "General Parameters"))
        self.label.setText(_translate("MainWindow", "STATE:"))
        self.label_16.setText(_translate("MainWindow", "CONNECTION:"))
        self.label_4.setText(_translate("MainWindow", "PULSES:"))
        self.label_6.setText(_translate("MainWindow", "REPEATS:"))
        self.label_8.setText(_translate("MainWindow", "PRI PW:"))
        self.label_10.setText(_translate("MainWindow", "PREPULSE:"))
        self.label_12.setText(_translate("MainWindow", "X AMP DELAY:"))
        self.label_14.setText(_translate("MainWindow", "L AMP DELAY:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pulse Parameters"))
        item = self.table_pulse_params.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pulse width"))
        item = self.table_pulse_params.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PRI"))
        item = self.table_pulse_params.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.table_pulse_params.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Frequency"))
        self.but_override.setText(_translate("MainWindow", "OVERRIDE"))
        self.but_refresh.setText(_translate("MainWindow", "REFRESH"))
        self.but_fire_abort.setText(_translate("MainWindow", "FIRE/ABORT"))
        self.but_arm_disarm.setText(_translate("MainWindow", "ARM/DISARM"))

